// AREA DATA
#define AREA_ORIGIN_INDEX 0
#define AREA_MINDIST_INDEX 1
#define AREA_YAXIS_INDEX 2
#define AREA_XAXIS_INDEX 3
#define AREA_DIR_INDEX 4

#define AREA_ORIGIN(X) (X select AREA_ORIGIN_INDEX)
#define AREA_MINDIST(X) (X select AREA_MINDIST_INDEX)
#define AREA_YAXIS(X) (X select AREA_YAXIS_INDEX)
#define AREA_XAXIS(X) (X select AREA_XAXIS_INDEX)
#define AREA_DIR(X) (X select AREA_DIR_INDEX)
