#include "..\settings.sqf"
//#include "..\settings_debug.sqf"
#include "..\settings_hearing.sqf"
#include "..\settings_panic.sqf"
#include "..\settings_targeting.sqf"

#include "exceptions.hpp"
#include "logTypes.hpp"
#include "macros.hpp"
#include "dataStructures\dataStructures.hpp"
