
#include "..\..\header\header.hpp"

#define MAX_PANIC 0.9

#define DAMAGE_DECREASE_FACTOR 100

#define MAX_DAMAGE 0.75
#define PANIC_FROM_DAMAGE(X) ((X / MAX_DAMAGE) min 1)
#define MAX_SUPPRESSION
#define PANIC_FROM_SUPPRESSION(X) ((X / MAX_SUPPRESSION) min 1)

#define PANIC_FNC(DAMAGE,SUPPRESSION) (((PANIC_FROM_DAMAGE(DAMAGE) + PANIC_FROM_SUPPRESSION(SUPPRESSION)) / 2) min MAX_PANIC)
